### ISSUE TITLE
As a researcher I need to apply filters so that I can find data that is relevant to my research.

### ISSUE THREAD

**Issue by adphillips2017** [hubmapconsortium/ccf-ui#143]
Ensure the researcher apply filters to the data they want to work with by:

- [x] Providing a button on the Filter Flyout labeled Apply Filters
- [x] Providing a hover state for the button that changes the background to blue and has a cursor that is a finger pointer to show the button is clickable
- [x] Closing the Filter Flyout on click of the Apply Filters button
    - [x] having it animate back to the right and having the filter icon become visible again
    - [x] updating the list in the Tissue Browser to reflect the applied filters, this includes changing the values of the text area at the top of the TB and the list of available items below, a spinner will appear while the data is updating (NOTE: top text should appear first, the list only when complete. Animate both in with a fade, ease in-out.) #171 

- [x] Update the text in the right drawer to reflect the new Sex, Age, BMI values #171 
- [ ] Update Stage with the correct body type based on Sex #171

**Comment by gurjaspalbedi** [comment]
What should be the behavior when the filter is in open state and user closes the right panel? 

![image](https://user-images.githubusercontent.com/42523353/76987467-969a1280-6919-11ea-9ec7-2d70443d1184.png)

**Comment by bherr2** [comment]
It might be interesting to keep it open, but for simplicity we should close the filter when the right panel closes.

**Comment by gurjaspalbedi** [comment]
I also feel that we should close the filter, that's why I wanted to see what others think.
